// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalProjectApi.Data;

#nullable disable

namespace PersonalProjectApi.Migrations
{
    [DbContext(typeof(TaskBoardDbContext))]
    [Migration("20260821075850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.BoardList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoardLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cffb00c7-25bb-4ee2-929a-f5b4bd9a1bfb"),
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("faa6be83-b7c5-4130-98a3-c6fa0982c67f"),
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("d009636a-b61a-444d-a186-40aae85263c8"),
                            Title = "Finished"
                        });
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PriorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardListId");

                    b.HasIndex("PriorityId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cf6d1e5-bd29-4978-9b38-e4459c0bfa71"),
                            BoardListId = new Guid("cffb00c7-25bb-4ee2-929a-f5b4bd9a1bfb"),
                            Description = "Make an DB with all necesary data, connect it with API and front. Test it.",
                            DueDate = new DateTime(2026, 8, 30, 18, 0, 30, 0, DateTimeKind.Unspecified),
                            PriorityId = new Guid("c1f2fa72-41e5-4dbf-bc93-19311c40a43e"),
                            Title = "Make back for personal project"
                        },
                        new
                        {
                            Id = new Guid("aa94bb74-7c70-4fa8-89ab-de6148c34f98"),
                            BoardListId = new Guid("cffb00c7-25bb-4ee2-929a-f5b4bd9a1bfb"),
                            Description = "Go to the gym and eat well after that.",
                            DueDate = new DateTime(2026, 8, 21, 10, 58, 50, 422, DateTimeKind.Local).AddTicks(4026),
                            PriorityId = new Guid("f4000d47-117a-42cd-81de-44a64d5a4219"),
                            Title = "Workout"
                        },
                        new
                        {
                            Id = new Guid("30e15610-ba6a-41b9-ac8d-060fd0e6fbea"),
                            BoardListId = new Guid("d009636a-b61a-444d-a186-40aae85263c8"),
                            Description = "Clean my wardrobe...",
                            DueDate = new DateTime(2026, 8, 21, 10, 58, 50, 422, DateTimeKind.Local).AddTicks(4065),
                            PriorityId = new Guid("9e1572d6-328d-431d-a5c8-46d2fa119a64"),
                            Title = "Do household chores"
                        });
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.Priority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardPriority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e1572d6-328d-431d-a5c8-46d2fa119a64"),
                            CardPriority = "Low"
                        },
                        new
                        {
                            Id = new Guid("f4000d47-117a-42cd-81de-44a64d5a4219"),
                            CardPriority = "Medium"
                        },
                        new
                        {
                            Id = new Guid("c1f2fa72-41e5-4dbf-bc93-19311c40a43e"),
                            CardPriority = "High"
                        });
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.Card", b =>
                {
                    b.HasOne("PersonalProjectApi.Models.Domain.BoardList", "BoardList")
                        .WithMany("Cards")
                        .HasForeignKey("BoardListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalProjectApi.Models.Domain.Priority", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardList");

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.BoardList", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
