// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalProjectApi.Data;

#nullable disable

namespace PersonalProjectApi.Migrations
{
    [DbContext(typeof(TaskBoardDbContext))]
    [Migration("20260825084935_AddingListPosition")]
    partial class AddingListPosition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.BoardList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoardLists");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cffb00c7-25bb-4ee2-929a-f5b4bd9a1bfb"),
                            Position = 0,
                            Title = "To Do"
                        },
                        new
                        {
                            Id = new Guid("faa6be83-b7c5-4130-98a3-c6fa0982c67f"),
                            Position = 1,
                            Title = "In Progress"
                        },
                        new
                        {
                            Id = new Guid("d009636a-b61a-444d-a186-40aae85263c8"),
                            Position = 2,
                            Title = "Finished"
                        });
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardListId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cf6d1e5-bd29-4978-9b38-e4459c0bfa71"),
                            BoardListId = new Guid("cffb00c7-25bb-4ee2-929a-f5b4bd9a1bfb"),
                            Description = "Make an DB with all necesary data, connect it with API and front. Test it.",
                            DueDate = new DateTime(2026, 8, 30, 18, 0, 30, 0, DateTimeKind.Unspecified),
                            Priority = 3,
                            Title = "Make back for personal project"
                        },
                        new
                        {
                            Id = new Guid("aa94bb74-7c70-4fa8-89ab-de6148c34f98"),
                            BoardListId = new Guid("cffb00c7-25bb-4ee2-929a-f5b4bd9a1bfb"),
                            Description = "Go to the gym and eat well after that.",
                            DueDate = new DateTime(2026, 8, 25, 11, 49, 35, 403, DateTimeKind.Local).AddTicks(5313),
                            Priority = 2,
                            Title = "Workout"
                        },
                        new
                        {
                            Id = new Guid("30e15610-ba6a-41b9-ac8d-060fd0e6fbea"),
                            BoardListId = new Guid("d009636a-b61a-444d-a186-40aae85263c8"),
                            Description = "Clean my wardrobe...",
                            DueDate = new DateTime(2026, 8, 25, 11, 49, 35, 403, DateTimeKind.Local).AddTicks(5354),
                            Priority = 1,
                            Title = "Do household chores"
                        });
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.Card", b =>
                {
                    b.HasOne("PersonalProjectApi.Models.Domain.BoardList", "BoardList")
                        .WithMany("Cards")
                        .HasForeignKey("BoardListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardList");
                });

            modelBuilder.Entity("PersonalProjectApi.Models.Domain.BoardList", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
